name: "DynamicBan"
main: co.cc.dynamicdev.dynamicbanplus.DynamicBan
version: 1.3.1
author: [DynamicDev]
depend: [Vault]
permissions:
    dynamicban.*:
        description: Access to all the DynamicBan commands.
commands:
    dynplayer:
        description: Display details for a player.
        usage: /<command> <Playername>
        aliases: [dp, dplayer, ddetails] 
    dynkick:
        description: Kick a player.
        usage: /<command> <Playername> [Reason]
        aliases: [dk, kick, kickplayer]
    dynban:
        description: Ban a player's account.
        usage: /<command> <Playername> [Reason]
        aliases: [db, ban, banplayer]
    dynbanip:
        description: Ban a player's IP.
        usage: /<command> <Playername> [Reason]
        aliases: [dbip, banip, dynb]
    dynunbanip:
        description: Unban a player's IP.
        usage: /<command> <Playername>
        aliases: [dubip, unban-ip]
    dynunban:
        description: Unban a player's account.
        usage: /<command> <Playername>
        aliases: [dub, unban, unbanplayer, pardon]
    dynstanding:
        description: View a player's standing.
        usage: /<command> <Playername>
        aliases: [pstanding, dst]
    dyntempban:
        description: Temporarily ban a player's account.
        usage: /<command> <Playername> <Time>
        aliases: [dtb, tempban, tempbanplayer]
    dyntempbanip:
        description: Temporarily ban a player's IP.
        usage: /<command> <Playername> <Time>
        aliases: [dtbip, tempbanip, tempipbanplayer]
    dynimmune:
        description: Add or remove a player's immunity.
        usage: /<command> <add/remove> <Playername>
        aliases: [dynimmunity, dim, di]
    dynwarn:
        description: Warn a player.
        usage: /<command> <Playername> [Reason]
        aliases: [dw, dwarn, dynwarnplayer]
    dynpurge:
        description: Reset a player's data.
        usage: /<command> <Playername> <data/warns/kicks>
        aliases: [dpg, dpurge]   
    dynlist:
        description: View a list of online players.
        usage: /<command>
        aliases: [dlist, diplist]    
    dynreload:
        description: Reload the DynamicBan data.
        usage: /<command>
        aliases: [drl, dreload]   
    dyncompare:
        description: Compare the IPs of two players.
        usage: /<command> <Playername> <anotherPlayername>
        aliases: [dc, dcompare, cip]  
    dynmute:
        description: Mute a player.
        usage: /<command> <Playername> <Time>
        aliases: [mute, dm]
    dynunmute:
        description: Unmute a player.
        usage: /<command> <Playername>
        aliases: [unmute, dum]   
    dynlockip:
        description: Lock an IP to a player.
        usage: /<command> <IP> <Playername>
        aliases: [lockip, dl]
    dynunlockip:
        description: Unlock an IP.
        usage: /<command> <IP>
        aliases: [unlockip, dul]
    dynrangeban:
        description: Ban a player's IP range.
        usage: /<command> <Playername> level:<1/2/3>
        aliases: [drb, dr, rangeban]
    dynunbanrange:
        description: Unban a player's IP range.
        usage: /<command> <Playername>
        aliases: [durb, dunrange, unban-range]         
    dynwhitelist:
        description: Protect a player from bans.
        usage: /<command> <add/remove> <Playername/IP/IP-Range>
        aliases: [dwl, dwhite, dprotect]   